### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by spences10** [justinjmoses/twitter-sentiment#1]
Hi, I'm trying to work out how to use this...

Currently using `twit` which is configured with the same keys listed in your docs:

```text
CONSUMER_KEY=
CONSUMER_SECRET=
ACCESS_TOKEN=744878492-
ACCESS_TOKEN_SECRET=
```

Where do I pass that into your app?

```javascript
const twitterSentiment = require('twitter-sentiment')

const Writable = require('stream').Writable

const readable = twitterSentiment({
  track: 'trump',
  minFollowers: 10000
})

readable.pipe(new Writable({
  objectMode: true,
  write(chunk, enc, next) {
    console.log(chunk.text)
    console.log(chunk.sentiment.score)
    next(null)
  }
}))
```

**Comment by jjgonecrypto** [comment]
Hey, you just need to make sure those four environment variables are set using the `TWITTER_` prefix, as in the docs.

**Comment by jjgonecrypto** [comment]
As long as they are set on your environment (either using `export` on Mac/UNIX or `set` in Win X before running the app)

**Comment by spences10** [comment]
So, I have the keys set in a `.env` file and I use `dontenv` to use the keys in the bot I have

Currently they are in my `.env` as such:

```
TWITTER_CONSUMER_KEY=...
TWITTER_CONSUMER_SECRET=...
TWITTER_ACCESS_TOKEN=...
TWITTER_ACCESS_TOKEN_SECRET=...
```

How do I use the `config` with `twitter-sentiment` I want to keep them in a `.env` file

Thanks

**Comment by jjgonecrypto** [comment]
It should work without needing to pass anything in, it reads the environment variables from `process.env` which is what `dotenv` (that's what you meant?) does.

See the source here: https://github.com/justinjmoses/twitter-sentiment/blob/master/index.js#L11-L14

What are you seeing when you try to use this library?
